### ISSUE TITLE
Wrong help message

### ISSUE THREAD

**Issue by Palandr1234** [PictureInspector/picture-inspector-bot#1]
It would be better if instead of some text Latin text the bot had some meaningful text as a help message

**Comment by Dinislam36** [comment]
The issue is fixed #

> It would be better if instead of some text Latin text the bot had some meaningful text as a help message

**Comment by Dinislam36** [comment]
> It would be better if instead of some text Latin text the bot had some meaningful text as a help message

The issue is fixed
